Ext.define('sport.view.france.liga',{
	extend:'Ext.TabPanel',
	xtype:'ligafr',
	config:{
		title:'Soccer',   		    
          xtype:'tabpanel',		
		
                	
                	 items: [{
                    
                    title: 'Classement',
                    scrollable:true,
                    

                    //next we give it some simple html
                    items: {
                        html: ['<table class="football" cellpadding="0" cellspacing="0" summary="Aucun"><thead><tr>',
                               '<th ><abbr title="Position">Pos.</abbr></th>',
                               '<th>Equipe</th>',
                               '<th ><abbr title="Points">Pts</abbr></th>',
                               ' <th ><abbr title="Joués">J</abbr></th>',
                               ' <th><abbr title="Victoires">V</abbr></th>',
                               '<th><abbr title="Nuls">N</abbr></th>',
                               '<th ><abbr title="Défaites">D</abbr></th>',
                               ' <th><abbr title="Différence">+/-</abbr></th>',
                        ' </tr>',
                        '  </thead>',
                        '  <tbody>',
                        '  <tr>',
                        '  <td >1</td>',
                        ' <th >',
                        ' <a href="/football/fc-barcelone/">FC Barcelone</a>',
                        ' </th>',
                        ' <td><b>43</b></td>',
                        ' <td>15</td>',
                        ' <td>14</td>',
                        '<td>1</td>',
                        '<td>0</td>',
                        ' <td>33</td>',
                        ' </tr>',
                        '  <tr >',
                        '   <td >2</td>',
                        '   <th >',
                        '  Atlético Madrid',
                        ' </th>',
                        ' <td><b>37</b></td>',
                        ' <td>15</td>',
                        ' <td>12</td>',
                        ' <td>1</td>',
                        '<td>2</td>',
                        '<td>22</td>',
                        ' </tr>',
                        ' <tr>',
                        ' <td >3</td>',
                        '  <th >',
                        '  <a href="/football/real-madrid/">Real Madrid</a>',
                        ' </th>',
                        ' <td><b>32</b></td>',
                        ' <td>15</td>',
                        ' <td>10</td>',
                        '  <td>2</td>',
                        ' <td>3</td>',
                        '  <td>25</td>',
                        '   </tr>',
                        '   <tr >',
                        '  <td >4</td>',
                        '  <th >',
                        '  Málaga',
                        '  </th>',
                        '  <td><b>25</b></td>',
                        '  <td>15</td>',
                        '  <td>7</td>',
                        '  <td>4</td>',
                        '  <td>4</td>',
                        '  <td>13</td>',
                        ' </tr>',
                        '  <tr>',
                        ' <td >5</td>',
                        ' <th >',
                        ' Betis Séville',
                        ' </th>',
                        ' <td><b>25</b></td>',
                        ' <td>15</td>',
                        ' <td>8</td>',
                        ' <td>1</td>',
                        ' <td>6</td>',
                        ' <td>-2</td>',
                        ' </tr>',
                        ' <tr >',
                        ' <td >6</td>',
                        '  <th >',
                        ' Levante UD',
                        ' </th>',
                        '<td><b>24</b></td>',
                        ' <td>15</td>',
                        ' <td>7</td>',
                        ' <td>3</td>',
                        '  <td>5</td>',
                        ' <td>-1</td>',
                        ' </tr>',
                        ' <tr>',
                        ' <td >7</td>',
                        ' <th >',
                        'Getafe CF',
                        '</th>',
                        ' <td><b>23</b></td>',
                        '<td>15</td>',
                        '<td>7</td>',
                        '<td>2</td>',
                        ' <td>6</td>',
                        '<td>-2</td>',
                        ' </tr>',
                        '<tr >',
                        ' <td >8</td>',
                        ' <th >',
                        ' Valladolid',
                        ' </th>',
                        '<td><b>21</b></td>',
                        '    <td>15</td>',
                        '    <td>6</td>',
                        '    <td>3</td>',
                        '   <td>6</td>',
                        '  <td>4</td>',
                        '  </tr>',
                        '   <tr>',
                        '   <td >9</td>',
                        '  <th >',
                        '  Real Sociedad',
                        '  </th>',
                        ' <td><b>21</b></td>',
                        ' <td>15</td>',
                        ' <td>6</td>',
                        '  <td>3</td>',
                        ' <td>6</td>',
                        ' <td>3</td>',
                        '</tr>',
                        '     <tr >',
                        '   <td >10</td>',
                        ' <th >',
                          '    Valence',
                        '    </th>',
                        '    <td><b>21</b></td>',
                        '  <td>15</td>',
                        '    <td>6</td>',
                        '  <td>3</td>',
                        '  <td>6</td>',
                        ' <td>-4</td>',
                        ' </tr>',
                        '  <tr>',
                        ' <td >11</td>',
                        '  <th >',
                        ' FC Séville',
                        ' </th>',
                        '<td><b>19</b></td>',
                        ' <td>15</td>',
                        ' <td>5</td>',
                        ' <td>4</td>',
                        '<td>6</td>',
                        ' <td>-1</td>',
                        ' </tr>',
                        ' <tr >',
                        '<td >12</td>',
                        ' <th >',
                        ' Saragosse',
                        ' </th>',
                        ' <td><b>19</b></td>',
                        ' <td>15</td>',
                        ' <td>6</td>',
                        ' <td>1</td>',
                        '<td>8</td>',
                        '<td>-5</td>',
                        ' </tr>',
                        ' <tr>',
                        '  <td >13</td>',
                        '  <th >',
                        '  Rayo Vallecano',
                        '   </th>',
                        ' <td><b>19</b></td>',
                        ' <td>15</td>',
                        '<td>6</td>',
                        ' <td>1</td>',
                        ' <td>8</td>',
                        ' <td>-14</td>',
                        ' </tr>',
                        ' <tr >',
                        ' <td >14</td>',
                        '  <th >',
                        ' Athletic Bilbao',
                        '  </th>',
                        ' <td><b>18</b></td>',
                        ' <td>15</td>',
                        ' <td>5</td>',
                        '  <td>3</td>',
                        '  <td>7</td>',
                        '  <td>-12</td>',
                        '  </tr>',
                        ' <tr>',
                        ' <td >15</td>',
                        ' <th >',
                        'Celta Vigo',
                        '</th>',
                        ' <td><b>15</b></td>',
                        ' <td>15</td>',
                        '<td>4</td>',
                        ' <td>3</td>',
                        '<td>8</td>',
                        '<td>-4</td>',
                        ' </tr>',
                        ' <tr >',
                        '<td >16</td>',
                        ' <th >',
                        ' Osasuna',
                        ' </th>',
                        ' <td><b>13</b></td>',
                        ' <td>15</td>',
                        '   <td>3</td>',
                        '   <td>4</td>',
                        '   <td>8</td>',
                        '   <td>-4</td>',
                        '  </tr>',
                        '  <tr>',
                        '  <td >17</td>',
                        '    <th >',
                        '    Majorque',
                        '    </th>',
                        '   <td><b>13</b></td>',
                        '   <td>15</td>',
                        '  <td>3</td>',
                        '  <td>4</td>',
                        '  <td>8</td>',
                        '<td>-13</td>',
                        '  </tr>',                   
                        ' </tbody>',
                        '</table>',].join(""),
                               styleHtmlContent:true,
                               fullscreen: true,
                              // centered: true
                    },
  

                    //then a custom cls so we can style it
                    cls: 'card1'
                },
                {
                    //title
                    title: 'Resultat',
                    scrollable:true,

                    //the items html
                    items: {
                    	
                        html: ['<h1 align = "center">Les derniers resultats</h1>',
                              ' <table ><tr ><td><h2 align = "center">Dimanche 9 d&eacute;cembre</h2></td></tr>',
                        	'<tr><td>AS Saint-Etienne</td ><td >0  -  1</td ><td >Olympique Lyonnais</td></tr>',
                              '<tr><td>Olympique de Marseille</td ><td >0  -  3</td ><td >FC Lorient</td></tr>',
                        	'<tr><td>Reims</td><td >0  -  0</td ><td >Girondins de Bordeaux</td></tr>',
                        	'<tr><td><h2 align = "center">Samedi 8 d&eacute;cembre</h2></td></tr>',
                        	'<tr><td>AS Nancy Lorraine</td ><td >1  -  1</td ><td >Valenciennes FC</td></tr> ',
                        	'<tr><td>FC Sochaux</td ><td >1  -  1</td ><td >Lille</td></tr>',
                        	'<tr><td>Stade Rennais</td ><td >2  -  2</td ><td >Stade Brestois</td></tr>',
                        	'<tr><td>Troyes</td ><td >1  -  1</td ><td >OGC Nice</td></tr>',
                        	'<tr><td>Montpellier H&eacute;rault</td ><td >3  -  0</td ><td >AC Ajaccio</td></tr>',
                        	'<tr><td>paris Saint-Germain</td ><td >4  -  0</td ><td >Evian TG</td></tr>',
                        	'<tr><td><h2 align = "center">Vendredi 7 d&eacute;cembre</h2></td></tr>',
                        	'<tr><td>Toulouse FC</td ><td >0  -  0</td ><td >Bastia</td></tr>',
                            '</table>',].join(""),
                           styleHtmlContent:true,  
                           fullscreen: true,
                            //centered: true
                    },

                    //custom cls
                    cls: 'card2'
                }
                
            ]
                
	}
})

