Ext.define('sport.view.france.ligue1',{
	extend:'Ext.TabPanel',
	xtype:'ligue',
	config:{
		title:'Soccer',
    	iconCls:'football',
		
       
          xtype:'tabpanel',		
		
                	
                	 items: [
                             {
                    
                    title: 'Classement',
                    scrollable:true,
                    fullscreen: true,

                    //next we give it some simple html
                    items: {
                        html: ['<table ><colgroup><col><col><col><col><col><col><col></colgroup><thead><tr><th scope="col">Equipe</th>',
                        '<th id="mediamodulesportseustandings-u" scope="col">J</th>',
                        '<th id="mediamodulesportseustandings-v"  scope="col">V</th>',
                       ' <th id="mediamodulesportseustandings-w"  scope="col">T.</th>',
                       ' <th id="mediamodulesportseustandings-x"  scope="col">D</th>',
                       ' <th id="mediamodulesportseustandings-y"  scope="col">pts</th>',
                       ' <th id="mediamodulesportseustandings-z"  scope="col">+/-</th></tr></thead><tbody><tr><th  ><a href="/football/olympique-lyonnais/">Olympique Lyonnais</th>',
                       ' <td>16</td>',
                       ' <td >10</td>',
                       ' <td >4</td>',
                        '<td >2</td>',
                       ' <td >34</td>',
                       ' <td >14</td></tr>',
                       ' <tr><th  >paris Saint-Germain</th>',
                        '<td>16</td>',
                       ' <td >8</td>',
                       ' <td >5</td>',
                        '<td >3</td>',
                        '<td >29</td>',
                      ' <td >16</td></tr>',
                       ' <tr><th >Olympique de Marseille</th>',
                        '<td>16</td>',
                      '  <td >9</td>',
                       ' <td >2</td>',
                        '<td >5</td>',
                      '  <td >29</td>',
                        '<td >1</td></tr>',
                       ' <tr><th  >AS Saint-Etienne</th>',
                       ' <td>16</td>',
                       ' <td >7</td>',
                        '<td >5</td>',
                        '<td >4</td>',
                        '<td >26</td>',
                        '<td >13</td></tr>',
                       ' <tr><th  > Valenciennes FC</th>',
                        '<td>16</td>',
                        '<td >7</td>',
                        '<td >5</td>',
                       ' <td >4</td>',
                       ' <td >26</td>',
                       ' <td >12</td></tr>',
                       ' <tr><th > Girondins de Bordeaux</th>',
                       ' <td>16</td>',
                       ' <td >6</td>',
                        '<td >8</td>',
                        '<td >2</td>',
                        '<td >26</td>',
                       ' <td >7</td></tr>',
                        '<tr><th  >Stade Rennais</th>',
                       ' <td>16</td>',
                       ' <td >8</td>',
                        '<td >2</td>',
                        '<td >6</td>',
                       ' <td >26</td>',
                        '<td >2</td></tr>',
                       ' <tr><th  >FC Lorient</th>',
                       ' <td>16</td>',
                       ' <td >6</td>',
                       ' <td >6</td>',
                        '<td >4</td>',
                        '<td >24</td>',
                        '<td >-1</td></tr>',
                      '  <tr><th  >Toulouse FC</th>',
                       ' <td>16</td>',
                       ' <td >6</td>',
                       ' <td >5</td>',
                      '  <td >5</td>',
                      ' <td >23</td>',
                       ' <td >6</td></tr>',
                       ' <tr><th  >OGC Nice</th>',
                       ' <td>16</td>',
                        '<td >5</td>',
                       ' <td >8</td>',
                       ' <td >3</td>',
                        '<td >23</td>',
                        '<td >1</td></tr>',
                       ' <tr><th  >Lille</th>',
                       ' <td>16</td>',
                       ' <td >5</td>',
                       ' <td >7</td>',
                        '<td >4</td>',
                       '<td >22</td>',
                       ' <td >1</td></tr>',
                       ' <tr><th  >Montpellier H&eacute;rault</th>',
                       ' <td>16</td>',
                        '<td >5</td>',
                       ' <td >5</td>',
                       ' <td >6</td>',
                       ' <td >20</td>',
                        '<td >3</td></tr>',
                        '<tr><th  >Bastia</th>',
                        '<td>16</td>',
                      '  <td >5</td>',
                       ' <td >4</td>',
                       ' <td >7</td>',
                       ' <td >19</td>',
                       ' <td >-12</td></tr>',
                       ' <tr><th  >Stade Brestois</th>',
                        '<td>16</td>',
                       ' <td >5</td>',
                       ' <td >3</td>',
                       ' <td >8</td>',
                        '<td >18</td>',
                        '<td >-5</td></tr>',
                       ' <tr><th  >Reims</th>',
                       ' <td>16</td>',
                       ' <td >4</td>',
                       ' <td >5</td>',
                        '<td >7</td>',
                       ' <td >17</td>',
                       ' <td >-2</td></tr>',
                      ' <tr><th  >FC Sochaux</th>',
                       ' <td>16</td>',
                       ' <td >4</td>',
                        '<td >4</td>',
                       ' <td >8</td>',
                      '  <td >16</td>',
                      '  <td >-7</td></tr>',
                     '   <tr><th  >AC Ajaccio</th>',
                      '  <td>16</td>',
                      '  <td >4</td>',
                       ' <td >6</td>',
                       ' <td >6</td>',
                       ' <td >16</td>',
                       ' <td >-7</td></tr>',
                       ' <tr><th  >Evian TG</th>',
                        '<td>16</td>',
                       ' <td >4</td>',
                       ' <td >4</td>',
                       ' <td >8</td>',
                       ' <td >16</td>',
                       ' <td >-10</td></tr>',
                        '<tr><th  >Troyes</th>',
                        '<td>16</td>',
                      '  <td >1</td>',
                       ' <td >6</td>',
                       ' <td >9</td>',
                       ' <td >9</td>',
                       ' <td >-16</td></tr>',
                      '  <tr><th  >AS Nancy Lorraine</th>',
                        '<td>16</td>',
                       ' <td >1</td>',
                       ' <td >6</td>',
                       ' <td >9</td>',
                       ' <td >9</td>',
                      '  <td >-16</td></tr></tbody><caption>Ligue 1</caption></table>',].join(""),
                               styleHtmlContent:true,                             
                               //centered: true
                    },
  

                    //then a custom cls so we can style it
                    cls: 'card1'
                },
                {
                    //title
                    title: 'Resultat',
                    scrollable:true,

                    //the items html
                    items: {
                    	
                        html: ['<h1 align = "center">Les derniers resultats</h1>',
                              ' <table ><tr ><td><h2 align = "center">Dimanche 9 d&eacute;cembre</h2></td></tr>',
                        	'<tr><td>AS Saint-Etienne</td ><td >0  -  1</td ><td >Olympique Lyonnais</td></tr>',
                              '<tr><td>Olympique de Marseille</td ><td >0  -  3</td ><td >FC Lorient</td></tr>',
                        	'<tr><td>Reims</td><td >0  -  0</td ><td >Girondins de Bordeaux</td></tr>',
                        	'<tr><td><h2 align = "center">Samedi 8 d&eacute;cembre</h2></td></tr>',
                        	'<tr><td>AS Nancy Lorraine</td ><td >1  -  1</td ><td >Valenciennes FC</td></tr> ',
                        	'<tr><td>FC Sochaux</td ><td >1  -  1</td ><td >Lille</td></tr>',
                        	'<tr><td>Stade Rennais</td ><td >2  -  2</td ><td >Stade Brestois</td></tr>',
                        	'<tr><td>Troyes</td ><td >1  -  1</td ><td >OGC Nice</td></tr>',
                        	'<tr><td>Montpellier H&eacute;rault</td ><td >3  -  0</td ><td >AC Ajaccio</td></tr>',
                        	'<tr><td>paris Saint-Germain</td ><td >4  -  0</td ><td >Evian TG</td></tr>',
                        	'<tr><td><h2 align = "center">Vendredi 7 d&eacute;cembre</h2></td></tr>',
                        	'<tr><td>Toulouse FC</td ><td >0  -  0</td ><td >Bastia</td></tr>',
                            '</table>',].join(""),
                           styleHtmlContent:true,   
                            //centered: true
                    },

                    //custom cls
                    cls: 'card2'
                }
                
            ]
                
	}
})