{
   "timestamp":"2012-12-30T15:14:42Z",
   "resultsOffset":0,
   "status":"success",
   "resultsLimit":10,
   "resultsCount":50,
   "headlines":[
      {
         "headline":"Kombouare plays down Bordeaux link",
         "keywords":[
            "Bordeaux",
            "French Ligue 1"
         ],
         "lastModified":"2012-12-28T15:11:04Z",
         "audio":[

         ],
         "premium":false,
         "mobileStory":"",
         "links":{
            "api":{
               "news":{
                  "href":"http://api.espn.com/v1/sports/news/1280307?region=GB"
               }
            },
            "web":{
               "href":"http://soccernet.espn.go.com/news/story/_/id/1280307/antoine-kombouare-plays-down-bordeaux-link?ex_cid=espnapi_public"
            },
            "mobile":{
               "href":"http://m.espn.go.com/soccer/story?storyId=1280307&ex_cid=espnapi_public"
            }
         },
         "type":"snHeadlineNews",
         "related":[

         ],
         "id":1280307,
         "story":"",
         "title":"Antoine Kombouare plays down Bordeaux link",
         "linkText":"Kombouare plays down Bordeaux link",
         "byline":"Ian Holyman, France Correspondent",
         "description":"Former Paris Saint-Germain coach Antoine Kombouare has ruled out an immediate return to Ligue 1 after being linked to the job at Bordeaux.",
         "images":[
            {
               "height":155,
               "alt":"Ligue 1",
               "width":275,
               "name":"Antoine Kombouare [275x155]",
               "caption":"Kombouare was fired by PSG last season despite the club being top of Ligue 1",
               "url":"http://soccernet.espn.go.com/design05/images/2012/1228/antoinekombouare_275x155.jpg"
            }
         ],
         "published":"2012-12-28T15:04:52Z",
         "video":[

         ]
      },
      {
         "headline":"Bordeaux 0-0 Troyes",
         "keywords":[
            "Bordeaux",
            "Troyes",
            "French Ligue 1"
         ],
         "lastModified":"2012-12-22T21:40:50Z",
         "premium":false,
         "mobileStory":"",
         "links":{
            "api":{
               "news":{
                  "href":"http://api.espn.com/v1/sports/news/1275181?region=GB"
               }
            },
            "web":{
               "href":"http://espnfc.com/uk/en/report/342778/bordeaux-0-0-troyes.html?ex_cid=espnapi_public"
            },
            "mobile":{
               "href":"http://m.espn.go.com/soccer/gamecast?gameId=342778&lang=EN&ex_cid=espnapi_public"
            }
         },
         "type":"snReport",
         "related":[

         ],
         "id":1275181,
         "story":"",
         "linkText":"Bordeaux 0-0 Troyes",
         "images":[

         ],
         "categories":[
            {
               "description":"Bordeaux",
               "type":"team",
               "sportId":600,
               "teamId":159,
               "team":{
                  "id":159,
                  "description":"Bordeaux",
                  "links":{
                     "api":{
                        "teams":{
                           "href":"http://api.espn.com/v1/sports/soccer/teams/159"
                        }
                     },
                     "web":{
                        "teams":{
                           "href":"http://soccernet.espn.go.com/team/_/id/159/bordeaux?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "teams":{
                           "href":"http://m.espn.go.com/soccer/clubhouse?teamId=159&ex_cid=espnapi_public"
                        }
                     }
                  }
               }
            },
            {
               "description":"Troyes",
               "type":"team",
               "sportId":600,
               "teamId":170,
               "team":{
                  "id":170,
                  "description":"Troyes",
                  "links":{
                     "api":{
                        "teams":{
                           "href":"http://api.espn.com/v1/sports/soccer/teams/170"
                        }
                     },
                     "web":{
                        "teams":{
                           "href":"http://soccernet.espn.go.com/team/_/id/170/troyes?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "teams":{
                           "href":"http://m.espn.go.com/soccer/clubhouse?teamId=170&ex_cid=espnapi_public"
                        }
                     }
                  }
               }
            },
            {
               "description":"FRA.1",
               "type":"league",
               "sportId":600,
               "leagueId":9,
               "league":{
                  "id":9,
                  "description":"FRA.1",
                  "links":{
                     "api":{
                        "leagues":{
                           "href":"http://api.espn.com/v1/sports/soccer/fra.1"
                        }
                     },
                     "web":{
                        "leagues":{
                           "href":"http://soccernet.espn.go.com/league/_/id/fra.1?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "leagues":{
                           "href":"http://m.espn.go.com/soccer/section?id=FRA.1&lang=ENex_cid=espnapi_public"
                        }
                     }
                  }
               }
            }
         ],
         "published":"2012-12-22T21:40:49Z",
         "video":[

         ]
      },
      {
         "headline":"Bordeaux v Troyes: Preview",
         "keywords":[
            "Bordeaux",
            "Troyes",
            "French Ligue 1"
         ],
         "lastModified":"2012-12-21T13:05:18Z",
         "premium":false,
         "mobileStory":"",
         "links":{
            "api":{
               "news":{
                  "href":"http://api.espn.com/v1/sports/news/1272686?region=GB"
               }
            },
            "web":{
               "href":"http://espnfc.com/uk/en/preview/342778/bordeaux-v-troyes-preview.html?ex_cid=espnapi_public"
            },
            "mobile":{
               "href":"http://m.espn.go.com/soccer/gamecast?gameId=342778&lang=EN&ex_cid=espnapi_public"
            }
         },
         "type":"snPreview",
         "related":[

         ],
         "id":1272686,
         "story":"",
         "linkText":"Bordeaux v Troyes: Preview",
         "images":[

         ],
         "categories":[
            {
               "description":"Bordeaux",
               "type":"team",
               "sportId":600,
               "teamId":159,
               "team":{
                  "id":159,
                  "description":"Bordeaux",
                  "links":{
                     "api":{
                        "teams":{
                           "href":"http://api.espn.com/v1/sports/soccer/teams/159"
                        }
                     },
                     "web":{
                        "teams":{
                           "href":"http://soccernet.espn.go.com/team/_/id/159/bordeaux?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "teams":{
                           "href":"http://m.espn.go.com/soccer/clubhouse?teamId=159&ex_cid=espnapi_public"
                        }
                     }
                  }
               }
            },
            {
               "description":"Troyes",
               "type":"team",
               "sportId":600,
               "teamId":170,
               "team":{
                  "id":170,
                  "description":"Troyes",
                  "links":{
                     "api":{
                        "teams":{
                           "href":"http://api.espn.com/v1/sports/soccer/teams/170"
                        }
                     },
                     "web":{
                        "teams":{
                           "href":"http://soccernet.espn.go.com/team/_/id/170/troyes?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "teams":{
                           "href":"http://m.espn.go.com/soccer/clubhouse?teamId=170&ex_cid=espnapi_public"
                        }
                     }
                  }
               }
            },
            {
               "description":"FRA.1",
               "type":"league",
               "sportId":600,
               "leagueId":9,
               "league":{
                  "id":9,
                  "description":"FRA.1",
                  "links":{
                     "api":{
                        "leagues":{
                           "href":"http://api.espn.com/v1/sports/soccer/fra.1"
                        }
                     },
                     "web":{
                        "leagues":{
                           "href":"http://soccernet.espn.go.com/league/_/id/fra.1?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "leagues":{
                           "href":"http://m.espn.go.com/soccer/section?id=FRA.1&lang=ENex_cid=espnapi_public"
                        }
                     }
                  }
               }
            }
         ],
         "published":"2012-12-21T13:05:17Z",
         "video":[

         ]
      },
      {
         "headline":"AS Nancy Lorraine 1-1 Bordeaux",
         "keywords":[
            "AS Nancy Lorraine",
            "Bordeaux",
            "French Ligue 1"
         ],
         "lastModified":"2012-12-16T22:55:11Z",
         "premium":false,
         "mobileStory":"",
         "links":{
            "api":{
               "news":{
                  "href":"http://api.espn.com/v1/sports/news/1266549?region=GB"
               }
            },
            "web":{
               "href":"http://espnfc.com/uk/en/report/342781/as-nancy-lorraine-1-1-bordeaux.html?ex_cid=espnapi_public"
            },
            "mobile":{
               "href":"http://m.espn.go.com/soccer/gamecast?gameId=342781&lang=EN&ex_cid=espnapi_public"
            }
         },
         "type":"snReport",
         "related":[

         ],
         "id":1266549,
         "story":"",
         "linkText":"AS Nancy Lorraine 1-1 Bordeaux",
         "images":[

         ],
         "categories":[
            {
               "description":"AS Nancy Lorraine",
               "type":"team",
               "sportId":600,
               "teamId":3267,
               "team":{
                  "id":3267,
                  "description":"AS Nancy Lorraine",
                  "links":{
                     "api":{
                        "teams":{
                           "href":"http://api.espn.com/v1/sports/soccer/teams/3267"
                        }
                     },
                     "web":{
                        "teams":{
                           "href":"http://soccernet.espn.go.com/team/_/id/3267/as-nancy-lorraine?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "teams":{
                           "href":"http://m.espn.go.com/soccer/clubhouse?teamId=3267&ex_cid=espnapi_public"
                        }
                     }
                  }
               }
            },
            {
               "description":"Bordeaux",
               "type":"team",
               "sportId":600,
               "teamId":159,
               "team":{
                  "id":159,
                  "description":"Bordeaux",
                  "links":{
                     "api":{
                        "teams":{
                           "href":"http://api.espn.com/v1/sports/soccer/teams/159"
                        }
                     },
                     "web":{
                        "teams":{
                           "href":"http://soccernet.espn.go.com/team/_/id/159/bordeaux?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "teams":{
                           "href":"http://m.espn.go.com/soccer/clubhouse?teamId=159&ex_cid=espnapi_public"
                        }
                     }
                  }
               }
            },
            {
               "description":"FRA.1",
               "type":"league",
               "sportId":600,
               "leagueId":9,
               "league":{
                  "id":9,
                  "description":"FRA.1",
                  "links":{
                     "api":{
                        "leagues":{
                           "href":"http://api.espn.com/v1/sports/soccer/fra.1"
                        }
                     },
                     "web":{
                        "leagues":{
                           "href":"http://soccernet.espn.go.com/league/_/id/fra.1?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "leagues":{
                           "href":"http://m.espn.go.com/soccer/section?id=FRA.1&lang=ENex_cid=espnapi_public"
                        }
                     }
                  }
               }
            }
         ],
         "published":"2012-12-16T15:39:34Z",
         "video":[

         ]
      },
      {
         "headline":"AS Nancy Lorraine v Bordeaux: Preview",
         "keywords":[
            "AS Nancy Lorraine",
            "Bordeaux",
            "French Ligue 1"
         ],
         "lastModified":"2012-12-15T09:40:34Z",
         "premium":false,
         "mobileStory":"",
         "links":{
            "api":{
               "news":{
                  "href":"http://api.espn.com/v1/sports/news/1264290?region=GB"
               }
            },
            "web":{
               "href":"http://espnfc.com/uk/en/preview/342781/as-nancy-lorraine-v-bordeaux-preview.html?ex_cid=espnapi_public"
            },
            "mobile":{
               "href":"http://m.espn.go.com/soccer/gamecast?gameId=342781&lang=EN&ex_cid=espnapi_public"
            }
         },
         "type":"snPreview",
         "related":[

         ],
         "id":1264290,
         "story":"",
         "linkText":"AS Nancy Lorraine v Bordeaux: Preview",
         "images":[

         ],
         "categories":[
            {
               "description":"AS Nancy Lorraine",
               "type":"team",
               "sportId":600,
               "teamId":3267,
               "team":{
                  "id":3267,
                  "description":"AS Nancy Lorraine",
                  "links":{
                     "api":{
                        "teams":{
                           "href":"http://api.espn.com/v1/sports/soccer/teams/3267"
                        }
                     },
                     "web":{
                        "teams":{
                           "href":"http://soccernet.espn.go.com/team/_/id/3267/as-nancy-lorraine?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "teams":{
                           "href":"http://m.espn.go.com/soccer/clubhouse?teamId=3267&ex_cid=espnapi_public"
                        }
                     }
                  }
               }
            },
            {
               "description":"Bordeaux",
               "type":"team",
               "sportId":600,
               "teamId":159,
               "team":{
                  "id":159,
                  "description":"Bordeaux",
                  "links":{
                     "api":{
                        "teams":{
                           "href":"http://api.espn.com/v1/sports/soccer/teams/159"
                        }
                     },
                     "web":{
                        "teams":{
                           "href":"http://soccernet.espn.go.com/team/_/id/159/bordeaux?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "teams":{
                           "href":"http://m.espn.go.com/soccer/clubhouse?teamId=159&ex_cid=espnapi_public"
                        }
                     }
                  }
               }
            },
            {
               "description":"FRA.1",
               "type":"league",
               "sportId":600,
               "leagueId":9,
               "league":{
                  "id":9,
                  "description":"FRA.1",
                  "links":{
                     "api":{
                        "leagues":{
                           "href":"http://api.espn.com/v1/sports/soccer/fra.1"
                        }
                     },
                     "web":{
                        "leagues":{
                           "href":"http://soccernet.espn.go.com/league/_/id/fra.1?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "leagues":{
                           "href":"http://m.espn.go.com/soccer/section?id=FRA.1&lang=ENex_cid=espnapi_public"
                        }
                     }
                  }
               }
            }
         ],
         "published":"2012-12-15T09:40:33Z",
         "video":[

         ]
      },
      {
         "headline":"Spoils shared at Bordeaux",
         "keywords":[
            "Bordeaux",
            "St Etienne",
            "French Ligue 1"
         ],
         "lastModified":"2012-12-13T22:37:15Z",
         "premium":false,
         "mobileStory":"",
         "links":{
            "api":{
               "news":{
                  "href":"http://api.espn.com/v1/sports/news/1262655?region=GB"
               }
            },
            "web":{
               "href":"http://espnfc.com/uk/en/report/342796/spoils-shared-bordeaux.html?ex_cid=espnapi_public"
            },
            "mobile":{
               "href":"http://m.espn.go.com/soccer/gamecast?gameId=342796&lang=EN&ex_cid=espnapi_public"
            }
         },
         "type":"snReport",
         "related":[

         ],
         "id":1262655,
         "story":"",
         "linkText":"Bordeaux 0-0 St Etienne: Girondins run continues",
         "images":[
            {
               "height":360,
               "alt":"Francis Gillot",
               "width":640,
               "name":"Francis Gillot point 20120826 [640x360]",
               "caption":"Francis Gillot",
               "url":"http://soccernet.espn.go.com/design05/images/2012/1213/francisgillotpoint20120826_640x360.jpg"
            }
         ],
         "categories":[
            {
               "description":"Bordeaux",
               "type":"team",
               "sportId":600,
               "teamId":159,
               "team":{
                  "id":159,
                  "description":"Bordeaux",
                  "links":{
                     "api":{
                        "teams":{
                           "href":"http://api.espn.com/v1/sports/soccer/teams/159"
                        }
                     },
                     "web":{
                        "teams":{
                           "href":"http://soccernet.espn.go.com/team/_/id/159/bordeaux?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "teams":{
                           "href":"http://m.espn.go.com/soccer/clubhouse?teamId=159&ex_cid=espnapi_public"
                        }
                     }
                  }
               }
            },
            {
               "description":"St Etienne",
               "type":"team",
               "sportId":600,
               "teamId":178,
               "team":{
                  "id":178,
                  "description":"St Etienne",
                  "links":{
                     "api":{
                        "teams":{
                           "href":"http://api.espn.com/v1/sports/soccer/teams/178"
                        }
                     },
                     "web":{
                        "teams":{
                           "href":"http://soccernet.espn.go.com/team/_/id/178/st-etienne?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "teams":{
                           "href":"http://m.espn.go.com/soccer/clubhouse?teamId=178&ex_cid=espnapi_public"
                        }
                     }
                  }
               }
            },
            {
               "description":"FRA.1",
               "type":"league",
               "sportId":600,
               "leagueId":9,
               "league":{
                  "id":9,
                  "description":"FRA.1",
                  "links":{
                     "api":{
                        "leagues":{
                           "href":"http://api.espn.com/v1/sports/soccer/fra.1"
                        }
                     },
                     "web":{
                        "leagues":{
                           "href":"http://soccernet.espn.go.com/league/_/id/fra.1?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "leagues":{
                           "href":"http://m.espn.go.com/soccer/section?id=FRA.1&lang=ENex_cid=espnapi_public"
                        }
                     }
                  }
               }
            }
         ],
         "published":"2012-12-13T22:28:44Z",
         "video":[

         ]
      },
      {
         "headline":"Bordeaux v St Etienne: Preview",
         "keywords":[
            "Bordeaux",
            "St Etienne",
            "French Ligue 1"
         ],
         "lastModified":"2012-12-12T16:30:01Z",
         "premium":false,
         "mobileStory":"",
         "links":{
            "api":{
               "news":{
                  "href":"http://api.espn.com/v1/sports/news/1261380?region=GB"
               }
            },
            "web":{
               "href":"http://espnfc.com/uk/en/preview/342796/bordeaux-v-st-etienne-preview.html?ex_cid=espnapi_public"
            },
            "mobile":{
               "href":"http://m.espn.go.com/soccer/gamecast?gameId=342796&lang=EN&ex_cid=espnapi_public"
            }
         },
         "type":"snPreview",
         "related":[

         ],
         "id":1261380,
         "story":"",
         "linkText":"Bordeaux v St Etienne: Preview",
         "images":[

         ],
         "categories":[
            {
               "description":"Bordeaux",
               "type":"team",
               "sportId":600,
               "teamId":159,
               "team":{
                  "id":159,
                  "description":"Bordeaux",
                  "links":{
                     "api":{
                        "teams":{
                           "href":"http://api.espn.com/v1/sports/soccer/teams/159"
                        }
                     },
                     "web":{
                        "teams":{
                           "href":"http://soccernet.espn.go.com/team/_/id/159/bordeaux?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "teams":{
                           "href":"http://m.espn.go.com/soccer/clubhouse?teamId=159&ex_cid=espnapi_public"
                        }
                     }
                  }
               }
            },
            {
               "description":"St Etienne",
               "type":"team",
               "sportId":600,
               "teamId":178,
               "team":{
                  "id":178,
                  "description":"St Etienne",
                  "links":{
                     "api":{
                        "teams":{
                           "href":"http://api.espn.com/v1/sports/soccer/teams/178"
                        }
                     },
                     "web":{
                        "teams":{
                           "href":"http://soccernet.espn.go.com/team/_/id/178/st-etienne?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "teams":{
                           "href":"http://m.espn.go.com/soccer/clubhouse?teamId=178&ex_cid=espnapi_public"
                        }
                     }
                  }
               }
            },
            {
               "description":"FRA.1",
               "type":"league",
               "sportId":600,
               "leagueId":9,
               "league":{
                  "id":9,
                  "description":"FRA.1",
                  "links":{
                     "api":{
                        "leagues":{
                           "href":"http://api.espn.com/v1/sports/soccer/fra.1"
                        }
                     },
                     "web":{
                        "leagues":{
                           "href":"http://soccernet.espn.go.com/league/_/id/fra.1?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "leagues":{
                           "href":"http://m.espn.go.com/soccer/section?id=FRA.1&lang=ENex_cid=espnapi_public"
                        }
                     }
                  }
               }
            }
         ],
         "published":"2012-12-12T16:30:00Z",
         "video":[

         ]
      },
      {
         "headline":"Stade de Reims 0-0 Bordeaux",
         "keywords":[
            "Bordeaux",
            "French Ligue 1"
         ],
         "lastModified":"2012-12-09T15:40:20Z",
         "premium":false,
         "mobileStory":"",
         "links":{
            "api":{
               "news":{
                  "href":"http://api.espn.com/v1/sports/news/1257266?region=GB"
               }
            },
            "web":{
               "href":"http://espnfc.com/uk/en/report/342801/stade-de-reims-0-0-bordeaux.html?ex_cid=espnapi_public"
            },
            "mobile":{
               "href":"http://m.espn.go.com/soccer/gamecast?gameId=342801&lang=EN&ex_cid=espnapi_public"
            }
         },
         "type":"snReport",
         "related":[

         ],
         "id":1257266,
         "story":"",
         "linkText":"Stade de Reims 0-0 Bordeaux",
         "images":[

         ],
         "categories":[
            {
               "description":"Stade de Reims",
               "type":"team",
               "sportId":600,
               "teamId":3243,
               "team":{
                  "id":3243,
                  "description":"Stade de Reims",
                  "links":{
                     "api":{
                        "teams":{
                           "href":"http://api.espn.com/v1/sports/soccer/teams/3243"
                        }
                     },
                     "web":{
                        "teams":{
                           "href":"http://soccernet.espn.go.com/team/_/id/3243/stade-de-reims?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "teams":{
                           "href":"http://m.espn.go.com/soccer/clubhouse?teamId=3243&ex_cid=espnapi_public"
                        }
                     }
                  }
               }
            },
            {
               "description":"Bordeaux",
               "type":"team",
               "sportId":600,
               "teamId":159,
               "team":{
                  "id":159,
                  "description":"Bordeaux",
                  "links":{
                     "api":{
                        "teams":{
                           "href":"http://api.espn.com/v1/sports/soccer/teams/159"
                        }
                     },
                     "web":{
                        "teams":{
                           "href":"http://soccernet.espn.go.com/team/_/id/159/bordeaux?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "teams":{
                           "href":"http://m.espn.go.com/soccer/clubhouse?teamId=159&ex_cid=espnapi_public"
                        }
                     }
                  }
               }
            },
            {
               "description":"FRA.1",
               "type":"league",
               "sportId":600,
               "leagueId":9,
               "league":{
                  "id":9,
                  "description":"FRA.1",
                  "links":{
                     "api":{
                        "leagues":{
                           "href":"http://api.espn.com/v1/sports/soccer/fra.1"
                        }
                     },
                     "web":{
                        "leagues":{
                           "href":"http://soccernet.espn.go.com/league/_/id/fra.1?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "leagues":{
                           "href":"http://m.espn.go.com/soccer/section?id=FRA.1&lang=ENex_cid=espnapi_public"
                        }
                     }
                  }
               }
            }
         ],
         "published":"2012-12-09T15:40:19Z",
         "video":[

         ]
      },
      {
         "headline":"Stade de Reims v Bordeaux: Preview",
         "keywords":[
            "Bordeaux",
            "French Ligue 1"
         ],
         "lastModified":"2012-12-08T09:01:23Z",
         "premium":false,
         "mobileStory":"",
         "links":{
            "api":{
               "news":{
                  "href":"http://api.espn.com/v1/sports/news/1255471?region=GB"
               }
            },
            "web":{
               "href":"http://espnfc.com/uk/en/preview/342801/stade-de-reims-v-bordeaux-preview.html?ex_cid=espnapi_public"
            },
            "mobile":{
               "href":"http://m.espn.go.com/soccer/gamecast?gameId=342801&lang=EN&ex_cid=espnapi_public"
            }
         },
         "type":"snPreview",
         "related":[

         ],
         "id":1255471,
         "story":"",
         "linkText":"Stade de Reims v Bordeaux: Preview",
         "images":[

         ],
         "categories":[
            {
               "description":"Stade de Reims",
               "type":"team",
               "sportId":600,
               "teamId":3243,
               "team":{
                  "id":3243,
                  "description":"Stade de Reims",
                  "links":{
                     "api":{
                        "teams":{
                           "href":"http://api.espn.com/v1/sports/soccer/teams/3243"
                        }
                     },
                     "web":{
                        "teams":{
                           "href":"http://soccernet.espn.go.com/team/_/id/3243/stade-de-reims?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "teams":{
                           "href":"http://m.espn.go.com/soccer/clubhouse?teamId=3243&ex_cid=espnapi_public"
                        }
                     }
                  }
               }
            },
            {
               "description":"Bordeaux",
               "type":"team",
               "sportId":600,
               "teamId":159,
               "team":{
                  "id":159,
                  "description":"Bordeaux",
                  "links":{
                     "api":{
                        "teams":{
                           "href":"http://api.espn.com/v1/sports/soccer/teams/159"
                        }
                     },
                     "web":{
                        "teams":{
                           "href":"http://soccernet.espn.go.com/team/_/id/159/bordeaux?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "teams":{
                           "href":"http://m.espn.go.com/soccer/clubhouse?teamId=159&ex_cid=espnapi_public"
                        }
                     }
                  }
               }
            },
            {
               "description":"FRA.1",
               "type":"league",
               "sportId":600,
               "leagueId":9,
               "league":{
                  "id":9,
                  "description":"FRA.1",
                  "links":{
                     "api":{
                        "leagues":{
                           "href":"http://api.espn.com/v1/sports/soccer/fra.1"
                        }
                     },
                     "web":{
                        "leagues":{
                           "href":"http://soccernet.espn.go.com/league/_/id/fra.1?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "leagues":{
                           "href":"http://m.espn.go.com/soccer/section?id=FRA.1&lang=ENex_cid=espnapi_public"
                        }
                     }
                  }
               }
            }
         ],
         "published":"2012-12-08T09:01:21Z",
         "video":[

         ]
      },
      {
         "headline":"Diabate double downs Newcastle",
         "keywords":[
            "Bordeaux",
            "Newcastle",
            "Europa League"
         ],
         "lastModified":"2012-12-06T21:47:31Z",
         "premium":false,
         "mobileStory":"",
         "links":{
            "api":{
               "news":{
                  "href":"http://api.espn.com/v1/sports/news/1253769?region=GB"
               }
            },
            "web":{
               "href":"http://espnfc.com/uk/en/report/355865/diabate-double-downs-newcastle.html?ex_cid=espnapi_public"
            },
            "mobile":{
               "href":"http://m.espn.go.com/soccer/gamecast?gameId=355865&lang=EN&ex_cid=espnapi_public"
            }
         },
         "type":"snReport",
         "related":[

         ],
         "id":1253769,
         "story":"",
         "linkText":"Bordeaux 2-0 Newcastle ",
         "images":[
            {
               "height":360,
               "alt":"Cheick Diabate celeb v Newcastle",
               "width":640,
               "name":"Cheick Diabate celeb v Newcastle [640x360]",
               "caption":"Cheick Diabate was in clinical mood against Newcastle",
               "url":"http://soccernet.espn.go.com/design05/images/2012/1206/cheickdiabatecelebvnewcastle_640x360.jpg"
            }
         ],
         "categories":[
            {
               "description":"Bordeaux",
               "type":"team",
               "sportId":600,
               "teamId":159,
               "team":{
                  "id":159,
                  "description":"Bordeaux",
                  "links":{
                     "api":{
                        "teams":{
                           "href":"http://api.espn.com/v1/sports/soccer/teams/159"
                        }
                     },
                     "web":{
                        "teams":{
                           "href":"http://soccernet.espn.go.com/team/_/id/159/bordeaux?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "teams":{
                           "href":"http://m.espn.go.com/soccer/clubhouse?teamId=159&ex_cid=espnapi_public"
                        }
                     }
                  }
               }
            },
            {
               "description":"Newcastle United",
               "type":"team",
               "sportId":600,
               "teamId":361,
               "team":{
                  "id":361,
                  "description":"Newcastle United",
                  "links":{
                     "api":{
                        "teams":{
                           "href":"http://api.espn.com/v1/sports/soccer/teams/361"
                        }
                     },
                     "web":{
                        "teams":{
                           "href":"http://soccernet.espn.go.com/team/_/id/361/newcastle-united?ex_cid=espnapi_public"
                        }
                     },
                     "mobile":{
                        "teams":{
                           "href":"http://m.espn.go.com/soccer/clubhouse?teamId=361&ex_cid=espnapi_public"
                        }
                     }
                  }
               }
            },
            {
               "description":"Europa League",
               "type":"league",
               "sportId":776,
               "leagueId":776,
               "league":{
                  "id":776,
                  "description":"Europa League",
                  "links":{
                     "api":{
                        "leagues":{

                        }
                     },
                     "web":{
                        "leagues":{

                        }
                     },
                     "mobile":{
                        "leagues":{

                        }
                     }
                  }
               }
            }
         ],
         "published":"2012-12-06T19:59:21Z",
         "video":[

         ]
      }
   ]
}